name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Surge
      run: npm install -g surge

    - name: Test
      run: "echo Insert your test here later"

    - name: Deploy to surge.sh
      run: surge ./src/public https://exploregithubaction.surge.sh/ --token ${{Secrets.TOKEN_SURGE}}

    - name: End workflow
      run: "echo End workflow"
